***
*Project:* Free Energy Synchronization

*Author:* Jingwei Liu (Music department, UC San Diego)
***

# <span style="background-color:darkorange; color:white; padding:2px 6px">Tutorial</span> 


# 12 Tone First Species Counterpoint

In [17]:
import numpy as np
import pandas as pd
import csv
from scamp import *
import tensorflow as tf
from tensorflow import keras

In [2]:
n = 200;
cantus_range_list = np.arange(43,73)
counter_range_list = np.arange(55,85)
melodic_interval = np.array([1,2,3,4,5,7,8,12])
melodic_interval_small = np.array([1,2,3,4])
harmonic_interval = np.array([3,4,7,8,9,12])
cantus_lst = [];
counter_lst = [];
st = np.random.choice(cantus_range_list)
cantus_lst.append(st)
counter_lst.append(np.random.choice(st + harmonic_interval))

for i in range(n):
    num = np.shape(cantus_lst)[0]
    cantus_choose_lst = np.concatenate((cantus_lst[-1] + melodic_interval, cantus_lst[-1] - melodic_interval))
    cantus_choose_lst = np.maximum(cantus_choose_lst,43)
    cantus_choose_lst = np.minimum(cantus_choose_lst,72)
    cantus_choose_lst = np.unique(cantus_choose_lst)

    counter_choose_lst = np.concatenate((counter_lst[-1] + melodic_interval, counter_lst[-1] - melodic_interval))
    counter_choose_lst = np.maximum(counter_choose_lst,55)
    counter_choose_lst = np.minimum(counter_choose_lst,84)
    counter_choose_lst = np.unique(counter_choose_lst)

    harmonic_diff = np.array(counter_lst) - np.array(cantus_lst)
    harmonic_diff = harmonic_diff[-10:]

    lst = []
    for j in cantus_choose_lst:
        for k in counter_choose_lst:
            if k-j in harmonic_interval and np.shape(np.where(harmonic_diff == k-j))[1] < 3:
                if k-j != 7 and k-j != 12:
                    lst.append([j,k])
                else:
                    if (k - counter_lst[-1])*(j - cantus_lst[-1]) < 0 and (np.abs(k - counter_lst[-1]) <= 2 or np.abs(j - cantus_lst[-1]) <= 2):
                        lst.append([j,k])
    if lst != []:
        save_lst = lst
    else:
        save_lst = [[np.random.choice(cantus_choose_lst),np.random.choice(counter_choose_lst)]]
    
    if num == 1:
        indes = np.random.randint(len(lst), size = 1)[0]
        [a,b] = lst[indes]
        cantus_lst.append(a)
        counter_lst.append(b)     
    else:
        cantus_dif_last = cantus_lst[-2] - cantus_lst[-1]
        counter_dif_last = counter_lst[-2] - counter_lst[-1]
        if np.abs(cantus_dif_last) >= 5:
            sign = np.sign(cantus_dif_last)
            a = cantus_lst[-1] + sign*1
            b = cantus_lst[-1] + sign*2
            cantus = np.array(lst)[:,0]
            Ind = [];
            for index in range(len(cantus)):
                if cantus[index] != a and cantus[index] != b:
                    Ind.append(index)
            lst = np.delete(lst, Ind, axis=0)
        if np.abs(counter_dif_last) >= 5:
            sign = np.sign(counter_dif_last)
            a = counter_lst[-1] + sign*1
            b = counter_lst[-1] + sign*2
            counter = np.array(lst)[:,1]
            Ind = [];
            for index in range(len(counter)):
                if counter[index] != a and counter[index] != b:
                    Ind.append(index)
            lst = np.delete(lst, Ind, axis=0)
            
        cantus_diff = np.diff(cantus_lst)[-10:]
        counter_diff = np.diff(counter_lst)[-10:]
        
        cantus_num_leap = np.shape(np.where(np.abs(cantus_diff) >= 5))[1]
        counter_num_leap = np.shape(np.where(np.abs(counter_diff) >= 5))[1]
        
        if cantus_num_leap >= 2:
            cantus = np.array(lst)[:,0]
            Ind = [];
            for index in range(len(cantus)):
                if np.abs(cantus[index] - cantus_lst[-1]) >= 5:
                    Ind.append(index)
            lst = np.delete(lst, Ind, axis=0)
        if counter_num_leap >= 2:
            counter = np.array(lst)[:,1]
            Ind = [];
            for index in range(len(counter)):
                if np.abs(counter[index] - counter_lst[-1]) >= 5:
                    Ind.append(index)
            lst = np.delete(lst, Ind, axis=0)
        
        cantus = np.array(lst)[:,0]
        Ind = [];
        for index in range(len(cantus)):
            if np.shape(np.where(cantus_lst[-10:] == cantus[index]))[1] >= 3:
                Ind.append(index)
        lst = np.delete(lst, Ind, axis=0)
        
        counter = np.array(lst)[:,1]
        Ind = [];
        for index in range(len(counter)):
            if np.shape(np.where(counter_lst[-10:] == counter[index]))[1] >= 3:
                Ind.append(index)
        lst = np.delete(lst, Ind, axis=0)
        
        if len(lst) == 0:
            lst = save_lst

        indes = np.random.randint(len(lst), size = 1)[0]
        [a,b] = lst[indes]
        cantus_lst.append(a)
        counter_lst.append(b)

In [3]:
cantus_lst

[43,
 51,
 55,
 53,
 48,
 50,
 48,
 45,
 46,
 44,
 48,
 44,
 56,
 54,
 56,
 55,
 67,
 65,
 63,
 62,
 66,
 65,
 62,
 61,
 65,
 66,
 64,
 68,
 71,
 70,
 68,
 70,
 67,
 70,
 72,
 69,
 64,
 65,
 60,
 61,
 60,
 57,
 58,
 57,
 56,
 60,
 56,
 58,
 54,
 57,
 61,
 64,
 60,
 53,
 55,
 60,
 59,
 57,
 60,
 57,
 55,
 56,
 52,
 50,
 51,
 46,
 48,
 53,
 51,
 54,
 50,
 47,
 51,
 54,
 53,
 50,
 62,
 61,
 64,
 67,
 66,
 69,
 62,
 64,
 65,
 64,
 67,
 66,
 63,
 72,
 70,
 72,
 69,
 68,
 72,
 71,
 68,
 66,
 63,
 67,
 65,
 67,
 63,
 62,
 60,
 57,
 53,
 58,
 56,
 59,
 60,
 59,
 55,
 54,
 56,
 53,
 58,
 56,
 55,
 58,
 62,
 59,
 57,
 60,
 58,
 60,
 52,
 53,
 57,
 61,
 54,
 56,
 58,
 60,
 59,
 62,
 66,
 68,
 71,
 68,
 70,
 68,
 65,
 70,
 69,
 71,
 67,
 62,
 64,
 66,
 64,
 65,
 66,
 64,
 61,
 69,
 67,
 69,
 71,
 68,
 69,
 70,
 66,
 59,
 60,
 57,
 60,
 57,
 53,
 61,
 59,
 58,
 57,
 61,
 64,
 65,
 58,
 60,
 56,
 59,
 56,
 53,
 61,
 59,
 63,
 64,
 61,
 53,
 55,
 51,
 48,
 46,
 48,
 47,
 59,
 57,
 58,
 56,
 64,
 63,


In [4]:
counter_lst

[46,
 55,
 63,
 61,
 57,
 59,
 56,
 57,
 55,
 56,
 55,
 56,
 59,
 57,
 64,
 63,
 71,
 69,
 67,
 70,
 69,
 72,
 74,
 70,
 68,
 69,
 73,
 76,
 79,
 82,
 77,
 78,
 79,
 74,
 75,
 76,
 73,
 72,
 69,
 65,
 63,
 66,
 62,
 60,
 68,
 67,
 64,
 61,
 63,
 65,
 70,
 68,
 64,
 61,
 64,
 63,
 62,
 64,
 68,
 66,
 67,
 59,
 60,
 62,
 59,
 55,
 57,
 56,
 63,
 61,
 59,
 55,
 55,
 57,
 60,
 62,
 66,
 73,
 72,
 71,
 75,
 78,
 71,
 72,
 68,
 72,
 71,
 73,
 75,
 76,
 77,
 81,
 78,
 76,
 81,
 79,
 72,
 73,
 71,
 70,
 68,
 71,
 67,
 71,
 68,
 66,
 62,
 61,
 68,
 66,
 64,
 62,
 58,
 66,
 64,
 65,
 67,
 64,
 63,
 67,
 65,
 68,
 69,
 67,
 62,
 63,
 60,
 57,
 60,
 65,
 63,
 65,
 66,
 63,
 67,
 71,
 69,
 76,
 75,
 72,
 74,
 75,
 77,
 78,
 81,
 80,
 76,
 71,
 72,
 74,
 76,
 69,
 70,
 71,
 73,
 77,
 76,
 78,
 74,
 71,
 78,
 77,
 74,
 62,
 64,
 61,
 64,
 65,
 61,
 64,
 62,
 65,
 66,
 70,
 73,
 68,
 70,
 67,
 68,
 63,
 64,
 65,
 69,
 68,
 66,
 67,
 65,
 57,
 58,
 59,
 57,
 58,
 57,
 55,
 67,
 66,
 62,
 63,
 67,
 75,


In [178]:
np.array(counter_lst) - np.array(cantus_lst)

array([ 3,  4,  4, 12,  3,  8,  8,  4,  8,  9,  9,  9,  4,  3,  4,  3,  8,
        8, 12,  7,  4])

In [179]:
np.diff(cantus_lst)

array([-5,  2, -1,  8, -2,  2,  3, -2,  4, -2,  4,  1,  2, -5,  2, -1,  3,
       -3,  1,  4])

In [180]:
np.diff(counter_lst)

array([-4,  2,  7, -1,  3,  2, -1,  2,  5, -2,  4, -4,  1, -4,  1,  4,  3,
        1, -4,  1])

In [139]:
num = np.shape(cantus_lst)[0]
cantus_choose_lst = np.concatenate((cantus_lst[-1] + melodic_interval, cantus_lst[-1] - melodic_interval))
cantus_choose_lst = np.maximum(cantus_choose_lst,43)
cantus_choose_lst = np.minimum(cantus_choose_lst,72)
cantus_choose_lst = np.unique(cantus_choose_lst)

counter_choose_lst = np.concatenate((counter_lst[-1] + melodic_interval, counter_lst[-1] - melodic_interval))
counter_choose_lst = np.maximum(counter_choose_lst,55)
counter_choose_lst = np.minimum(counter_choose_lst,84)
counter_choose_lst = np.unique(counter_choose_lst)

harmonic_diff = np.array(counter_lst) - np.array(cantus_lst)
harmonic_diff = harmonic_diff[-10:]

lst = []
for j in cantus_choose_lst:
    for k in counter_choose_lst:
        if k-j in harmonic_interval and np.shape(np.where(harmonic_diff == k-j))[1] < 3:
            if k-j != 7 and k-j != 12:
                lst.append([j,k])
            else:
                if (k - counter_lst[-1])*(j - cantus_lst[-1]) < 0 and (np.abs(k - counter_lst[-1]) <= 2 or np.abs(j - cantus_lst[-1]) <= 2):
                    lst.append([j,k])

In [140]:
len(lst)

51

In [141]:
cantus_dif_last = cantus_lst[-2] - cantus_lst[-1]
counter_dif_last = counter_lst[-2] - counter_lst[-1]
if np.abs(cantus_dif_last) >= 5:
    sign = np.sign(cantus_dif_last)
    a = cantus_lst[-1] + sign*1
    b = cantus_lst[-1] + sign*2
    cantus = np.array(lst)[:,0]
    Ind = [];
    for index in range(len(cantus)):
        if cantus(index) != a and cantus(index) != b:
            Ind.append(index)
    lst = np.delete(lst, Ind, axis=0)

In [157]:
lst

array([[53, 65],
       [56, 65],
       [57, 65],
       [57, 66],
       [58, 65],
       [58, 66],
       [59, 66],
       [61, 65],
       [62, 65],
       [62, 66],
       [63, 66]])

In [145]:
if np.abs(counter_dif_last) >= 5:
    sign = np.sign(counter_dif_last)
    a = counter_lst[-1] + sign*1
    b = counter_lst[-1] + sign*2
    counter = np.array(lst)[:,1]
    Ind = [];
    for index in range(len(counter)):
        if counter[index] != a and counter[index] != b:
            Ind.append(index)
    lst = np.delete(lst, Ind, axis=0)

In [146]:
len(lst)

11

In [147]:
cantus_diff = np.diff(cantus_lst)[-10:]
counter_diff = np.diff(counter_lst)[-10:]

cantus_num_leap = np.shape(np.where(np.abs(cantus_diff) >= 5))[1]
counter_num_leap = np.shape(np.where(np.abs(counter_diff) >= 5))[1]

In [148]:
cantus_diff

array([ 2, -2])

In [149]:
if cantus_num_leap >= 2:
    cantus = np.array(lst)[:,0]
    Ind = [];
    for index in range(len(cantus)):
        if np.abs(cantus[index] - cantus_lst[-1]) >= 5:
            Ind.append(index)
    lst = np.delete(lst, Ind, axis=0)

In [150]:
len(lst)

11

In [151]:
if counter_num_leap >= 2:
    counter = np.array(lst)[:,1]
    Ind = [];
    for index in range(len(counter)):
        if np.abs(counter[index] - counter_lst[-1]) >= 5:
            Ind.append(index)
    lst = np.delete(lst, Ind, axis=0)

In [152]:
len(lst)

11

In [153]:
cantus = np.array(lst)[:,0]
Ind = [];
for index in range(len(cantus)):
    if np.shape(np.where(cantus_lst[-10:] == cantus[index]))[1] >= 3:
        Ind.append(index)
lst = np.delete(lst, Ind, axis=0)

In [154]:
len(lst)

11

In [155]:
counter = np.array(lst)[:,1]
Ind = [];
for index in range(len(counter)):
    if np.shape(np.where(counter_lst[-10:] == counter[index]))[1] >= 3:
        Ind.append(index)
lst = np.delete(lst, Ind, axis=0)

In [156]:
len(lst)

11

In [89]:
cantus_choose_lst

array([43, 44, 45, 46, 47, 48, 50, 51, 55])

In [90]:
counter_choose_lst

array([55, 59])

In [91]:
lst

[[46, 55], [47, 55], [50, 59], [51, 55], [51, 59], [55, 59]]

In [102]:
np.array(lst)[:,0]

array([46, 47, 50, 51, 51, 55])

In [69]:
lst = [50]

In [13]:
np.shape(lst)[0]

1

In [74]:
choose_lst = np.concatenate((lst[0] + np.array([1,2,3,4,5,7,8,12]), lst[0] - np.array([1,2,3,4,5,7,8,12])))
choose_lst = np.maximum(choose_lst,43)
choose_lst = np.minimum(choose_lst,72)
choose_lst = np.unique(choose_lst)

In [75]:
choose_lst

array([43, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 57, 58, 62])

In [76]:
choose_lst[-10:]

array([48, 49, 51, 52, 53, 54, 55, 57, 58, 62])

In [78]:
np.shape(np.where(choose_lst[-10:] == 52))[1]

(1, 1)

In [36]:
np.sign(choose_lst[-2] - choose_lst[-1])

-1

In [42]:
44 not in choose_lst

True

In [54]:
dif = np.diff(choose_lst)
dif

array([2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 4])

In [52]:
np.where(choose_lst > 55)

(array([11, 12, 13], dtype=int64),)

In [55]:
np.shape(np.where(dif == 2))[1]

3

In [92]:
for item in lst:
    print(item)

[46, 55]
[47, 55]
[50, 59]
[51, 55]
[51, 59]
[55, 59]


In [94]:
[a,b] = item
a

55

In [61]:
cantus_lst = [1,2];
counter_lst = [4,7];
(np.array(counter_lst) - np.array(cantus_lst))[-1]

5

In [63]:
lst = []
lst.append([1,2])
lst.append([3,4])

In [64]:
lst

[[1, 2], [3, 4]]

In [51]:
s = Session()
s.tempo = 180
piano1 = s.new_part("piano")
piano2 = s.new_part("piano")

def cantus():
    for i in cantus_lst[1000:1020]:
        piano2.play_note(i,1,4)
        
def counter():
    for i in counter_lst[1000:1020]:
        piano1.play_note(i,1,4)
        
        
s.fast_forward_to_beat(100)

s.start_transcribing()
s.fork(counter)
s.fork(cantus)
s.wait_for_children_to_finish()
performance = s.stop_transcribing()
performance.to_score(title = "First Species Counterpoint", composer = "My programme",time_signature = "4/4").show_xml()

Using preset Piano Merlin for piano
Using preset Piano Merlin for piano


In [52]:
np.array(counter_lst[1000:1020]) - np.array(cantus_lst[1000:1020])

array([ 9,  8,  3,  4,  8,  3,  7, 12,  4,  3,  4,  8,  8,  9,  3,  8,  3,
        4,  7, 12])

In [46]:
np.diff(counter_lst[1000:1020])

array([-7,  1,  7, -1,  3,  1, -1,  1, -2, -4, -4,  4, -3,  3, -1, -7,  2,
       -8,  1])

In [47]:
np.diff(counter_lst[1000:1020])

array([-7,  1,  7, -1,  3,  1, -1,  1, -2, -4, -4,  4, -3,  3, -1, -7,  2,
       -8,  1])

In [6]:
Species = pd.DataFrame(columns=['Cantus','Counter'])
for i in range (n):
    Species = Species.append({'Cantus': cantus_lst[i],
         'Counter': counter_lst[i],
         }, ignore_index=True)

In [7]:
Species

Cantus Counter
0       43      46
1       51      55
2       55      63
3       53      61
4       48      57
..     ...     ...
195     57      66
196     58      62
197     56      63
198     64      67
199     63      75

[200 rows x 2 columns]

In [8]:
Species.to_csv('Species.csv')

In [11]:
df = pd.read_csv('Species.csv', sep=",",index_col = 0)
print(df)

     Cantus  Counter
0        43       46
1        51       55
2        55       63
3        53       61
4        48       57
..      ...      ...
195      57       66
196      58       62
197      56       63
198      64       67
199      63       75

[200 rows x 2 columns]


In [31]:
X = tf.Variable(np.zeros((2,n*2)))  # any data tensor

In [32]:
for i in range(0,2*n,2):
    X[0,i].assign(df['Cantus'][i/2])
    X[1,i].assign(0)
    X[0,i+1].assign(df['Counter'][i/2])
    X[1,i+1].assign(1)
X

<tf.Variable 'Variable:0' shape=(2, 400) dtype=float64, numpy=
array([[43., 46., 51., 55., 55., 63., 53., 61., 48., 57., 50., 59., 48.,
        56., 45., 57., 46., 55., 44., 56., 48., 55., 44., 56., 56., 59.,
        54., 57., 56., 64., 55., 63., 67., 71., 65., 69., 63., 67., 62.,
        70., 66., 69., 65., 72., 62., 74., 61., 70., 65., 68., 66., 69.,
        64., 73., 68., 76., 71., 79., 70., 82., 68., 77., 70., 78., 67.,
        79., 70., 74., 72., 75., 69., 76., 64., 73., 65., 72., 60., 69.,
        61., 65., 60., 63., 57., 66., 58., 62., 57., 60., 56., 68., 60.,
        67., 56., 64., 58., 61., 54., 63., 57., 65., 61., 70., 64., 68.,
        60., 64., 53., 61., 55., 64., 60., 63., 59., 62., 57., 64., 60.,
        68., 57., 66., 55., 67., 56., 59., 52., 60., 50., 62., 51., 59.,
        46., 55., 48., 57., 53., 56., 51., 63., 54., 61., 50., 59., 47.,
        55., 51., 55., 54., 57., 53., 60., 50., 62., 62., 66., 61., 73.,
        64., 72., 67., 71., 66., 75., 69., 78., 62., 71., 64.

In [33]:
dataset = tf.data.Dataset.from_tensor_slices(tf.transpose(X))
dataset

<TensorSliceDataset shapes: (2,), types: tf.float64>

In [34]:
for item in dataset.take(5):
    print(item)

tf.Tensor([43.  0.], shape=(2,), dtype=float64)
tf.Tensor([46.  1.], shape=(2,), dtype=float64)
tf.Tensor([51.  0.], shape=(2,), dtype=float64)
tf.Tensor([55.  1.], shape=(2,), dtype=float64)
tf.Tensor([55.  0.], shape=(2,), dtype=float64)
