In [1]:
import numpy as np
import pandas as pd
import csv
from scamp import *
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense,Flatten,Softmax,Input
import keras.backend as K 

Using TensorFlow backend.


In [2]:
df = pd.read_csv('Species.csv', sep=",",index_col = 0)
print(df)

      Cantus  Counter
0         58       67
1         66       69
2         64       71
3         68       76
4         66       74
...      ...      ...
9995      64       72
9996      56       60
9997      57       61
9998      61       65
9999      56       64

[10000 rows x 2 columns]


In [3]:
n = df.shape[0]
n

10000

In [4]:
X = tf.Variable(np.zeros((2,n*2)),dtype='int32')  # any data tensor
for i in range(0,2*n,2):
    X[0,i].assign(df['Cantus'][i/2] - 43)
    X[1,i].assign(0)
    X[0,i+1].assign(df['Counter'][i/2] - 55)
    X[1,i+1].assign(1)
X

<tf.Variable 'Variable:0' shape=(2, 20000) dtype=int32, numpy=
array([[15, 12, 23, ..., 10, 13,  9],
       [ 0,  1,  0, ...,  1,  0,  1]])>

In [5]:
depth = 30
X = tf.concat([tf.one_hot(X[0,:], depth),tf.dtypes.cast(tf.reshape(X[1,:],[20000,1]),tf.float32)],1)
X

<tf.Tensor: shape=(20000, 31), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)>

In [6]:
train_dataset = tf.data.Dataset.from_tensor_slices(X[:7000,:])
valid_dataset = tf.data.Dataset.from_tensor_slices(X[7000:9000,:])
test_dataset = tf.data.Dataset.from_tensor_slices(X[9000:,:])

In [7]:
def data_process(dataset,batch_size):
    n_steps = 20
    window_length = n_steps + 2 # target = input shifted 1 character ahead
    dataset = dataset.window(window_length, shift=2, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(window_length))
    
    shuffle_dataset = dataset.shuffle(7000).batch(batch_size)
    map_dataset = shuffle_dataset.map(lambda windows: (windows[:,:-2,:], windows[:,-2:-1,:],windows[:,-2,:],windows[:,-1,:]))
    final_dataset = map_dataset.map(
        lambda X_batch, Y_batch, Z_batch, U_batch: ((X_batch, Y_batch), (Z_batch[:,:-1], U_batch[:,:-1])))
    return final_dataset

In [11]:
batch_size = 20
train = data_process(train_dataset,batch_size)
valid = data_process(valid_dataset,batch_size)
test = data_process(test_dataset,batch_size)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [58]:
rnn_units = 12
n_notes = 30

input_A = keras.layers.Input(shape=(20,31), name="input_A") # (15, 20, 31)
input_B = keras.layers.Input(shape=(1,31), name="input_B") # (15, 1, 31)

hidden1 = keras.layers.LSTM(rnn_units, return_sequences=True)(input_A) # (15,20,12)
hidden2 = keras.layers.LSTM(rnn_units, return_sequences=True)(hidden1) #(15,20,12)

output_RNN = keras.layers.Dense(n_notes, activation='softmax')(hidden2) #(15,20,30)


e = keras.layers.Dense(1, activation='tanh')(hidden2) #(15,20,1)
e = keras.layers.Reshape([-1])(e) #(15,20)

alpha = keras.layers.Activation('softmax')(e) #(15,20)
c = keras.layers.Permute([2, 1])(keras.layers.RepeatVector(rnn_units)(alpha)) #(15,20,12)
c = keras.layers.Multiply()([hidden2, c]) #(15,20,12)
c = keras.layers.Lambda(lambda xin: K.sum(xin, axis=1), output_shape=(rnn_units,))(c) #(15,12)

output_A = keras.layers.Dense(n_notes, activation = 'softmax', name = 'output_A')(c) #(15,30) (0, cantus)

aux = keras.layers.SimpleRNN(rnn_units)(input_B, initial_state=c) #(15,12)
output_B = keras.layers.Dense(n_notes, activation = 'softmax', name = 'output_B')(aux) #(15,30) (1, counter)

model = keras.models.Model([input_A, input_B], [output_RNN, output_A, output_B])
att_model = keras.models.Model([input_A, input_B], alpha)
sub_model = keras.models.Model(input_A, output_A)

In [59]:
model.summary()

Model: "functional_9"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_A (InputLayer)            [(None, 20, 31)]     0                                            
__________________________________________________________________________________________________
lstm_6 (LSTM)                   (None, 20, 12)       2112        input_A[0][0]                    
__________________________________________________________________________________________________
lstm_7 (LSTM)                   (None, 20, 12)       1200        lstm_6[0][0]                     
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 20, 1)        13          lstm_7[0][0]                     
_______________________________________________________________________________________

In [179]:
model.compile(loss=['categorical_crossentropy', 'categorical_crossentropy','categorical_crossentropy'],
              optimizer="sgd")

In [61]:
sub_model.compile(loss='categorical_crossentropy',
              optimizer="sgd")

In [180]:
checkpoint_cb = keras.callbacks.ModelCheckpoint("my_keras_model.h5",
                                                save_best_only=True)
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,
                                                  restore_best_weights=True)
history = model.fit(train, epochs=1000,
                    validation_data = valid,
                    callbacks=[checkpoint_cb, early_stopping_cb])
# model = keras.models.load_model("my_keras_model.h5") # roll back to best model

Epoch 1/1000
175/175 [==============================] - 3s 18ms/step - loss: 5.9450 - output_A_loss: 3.2311 - output_B_loss: 2.7139 - val_loss: 6.0012 - val_output_A_loss: 3.2654 - val_output_B_loss: 2.7358
Epoch 2/1000
175/175 [==============================] - 2s 9ms/step - loss: 5.9199 - output_A_loss: 3.2305 - output_B_loss: 2.6894 - val_loss: 5.9769 - val_output_A_loss: 3.2650 - val_output_B_loss: 2.7119
Epoch 3/1000
175/175 [==============================] - 2s 10ms/step - loss: 5.8945 - output_A_loss: 3.2297 - output_B_loss: 2.6648 - val_loss: 5.9524 - val_output_A_loss: 3.2643 - val_output_B_loss: 2.6881
Epoch 4/1000
175/175 [==============================] - 2s 10ms/step - loss: 5.8695 - output_A_loss: 3.2291 - output_B_loss: 2.6403 - val_loss: 5.9278 - val_output_A_loss: 3.2638 - val_output_B_loss: 2.6640
Epoch 5/1000
175/175 [==============================] - 2s 9ms/step - loss: 5.8443 - output_A_loss: 3.2284 - output_B_loss: 2.6159 - val_loss: 5.9036 - val_output_A_loss: 3.

175/175 [==============================] - 2s 9ms/step - loss: 4.8067 - output_A_loss: 2.9110 - output_B_loss: 1.8957 - val_loss: 4.9523 - val_output_A_loss: 3.0047 - val_output_B_loss: 1.9476
Epoch 80/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.8016 - output_A_loss: 2.9089 - output_B_loss: 1.8928 - val_loss: 4.8958 - val_output_A_loss: 2.9626 - val_output_B_loss: 1.9332
Epoch 81/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.7924 - output_A_loss: 2.9024 - output_B_loss: 1.8900 - val_loss: 4.8892 - val_output_A_loss: 2.9584 - val_output_B_loss: 1.9308
Epoch 82/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.7834 - output_A_loss: 2.8968 - output_B_loss: 1.8865 - val_loss: 4.9174 - val_output_A_loss: 2.9808 - val_output_B_loss: 1.9366
Epoch 83/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.7767 - output_A_loss: 2.8931 - output_B_loss: 1.8835 - val_loss: 4.8728 - val_output_A_loss: 2.9505 - val_o

175/175 [==============================] - 2s 9ms/step - loss: 4.4508 - output_A_loss: 2.7134 - output_B_loss: 1.7374 - val_loss: 4.5858 - val_output_A_loss: 2.7889 - val_output_B_loss: 1.7969
Epoch 158/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.4441 - output_A_loss: 2.7078 - output_B_loss: 1.7363 - val_loss: 4.5880 - val_output_A_loss: 2.7887 - val_output_B_loss: 1.7993
Epoch 159/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.4458 - output_A_loss: 2.7086 - output_B_loss: 1.7372 - val_loss: 4.6058 - val_output_A_loss: 2.8051 - val_output_B_loss: 1.8007
Epoch 160/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.4472 - output_A_loss: 2.7128 - output_B_loss: 1.7344 - val_loss: 4.5996 - val_output_A_loss: 2.7989 - val_output_B_loss: 1.8008
Epoch 161/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.4381 - output_A_loss: 2.7034 - output_B_loss: 1.7347 - val_loss: 4.6348 - val_output_A_loss: 2.8272 - v

175/175 [==============================] - 2s 10ms/step - loss: 4.3250 - output_A_loss: 2.6442 - output_B_loss: 1.6808 - val_loss: 4.5396 - val_output_A_loss: 2.7710 - val_output_B_loss: 1.7686
Epoch 236/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.3214 - output_A_loss: 2.6414 - output_B_loss: 1.6800 - val_loss: 4.5060 - val_output_A_loss: 2.7565 - val_output_B_loss: 1.7495
Epoch 237/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.3233 - output_A_loss: 2.6441 - output_B_loss: 1.6792 - val_loss: 4.5118 - val_output_A_loss: 2.7647 - val_output_B_loss: 1.7472
Epoch 238/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.3225 - output_A_loss: 2.6441 - output_B_loss: 1.6784 - val_loss: 4.4930 - val_output_A_loss: 2.7448 - val_output_B_loss: 1.7482
Epoch 239/1000
175/175 [==============================] - 2s 9ms/step - loss: 4.3194 - output_A_loss: 2.6423 - output_B_loss: 1.6772 - val_loss: 4.4945 - val_output_A_loss: 2.7405 - 

In [181]:
total_loss, output_A_loss, output_B_loss = model.evaluate(test)

275/275 [==============================] - 1s 2ms/step - loss: 4.4284 - output_A_loss: 2.6921 - output_B_loss: 1.7363


In [185]:
X_start_A = tf.reshape(X[0:20,:],[1,20,31])
X_start_B = tf.reshape(X[20,:],[1,1,31])
y_pred_A, y_pred_B = model.predict((X_start_A, X_start_B))

In [186]:
y_pred_A = y_pred_A.reshape([30,])

In [187]:
y_pred_A

array([0.00067716, 0.00190915, 0.00152396, 0.0103321 , 0.01087172,
       0.01535911, 0.02206642, 0.03449211, 0.04800986, 0.06169345,
       0.07379999, 0.09606186, 0.0977999 , 0.11237505, 0.08416948,
       0.09317786, 0.06048174, 0.05260655, 0.04169814, 0.02771354,
       0.01801369, 0.01380401, 0.00901957, 0.00418178, 0.00273614,
       0.00162271, 0.00138894, 0.00104527, 0.00056717, 0.0008017 ],
      dtype=float32)

In [188]:
y_pred_B

array([[3.6131772e-03, 1.5351252e-03, 1.9504228e-03, 4.5388993e-03,
        2.3485422e-01, 2.8297099e-01, 7.5206679e-04, 4.2217756e-03,
        6.5058291e-02, 1.7451659e-01, 1.8333592e-01, 6.5362104e-04,
        2.9205132e-04, 3.6818638e-02, 1.6233191e-03, 5.3966208e-04,
        3.1124626e-04, 2.4665165e-05, 3.9106247e-04, 3.7426283e-04,
        1.5308102e-05, 1.7074865e-04, 2.5440744e-05, 1.7445337e-04,
        2.0087395e-04, 2.2326725e-05, 1.5282101e-04, 2.5725600e-04,
        2.3929816e-04, 3.6562790e-04]], dtype=float32)

In [189]:
pred_A_class_random = np.random.choice(30, 1, p=y_pred_A)[0]
pred_A_class_random

12

In [190]:
pred_A_class_max = np.where(y_pred_A == np.max(y_pred_A))[0][0]
pred_A_class_max

13

In [182]:
model.save("my_keras_model.h5")

In [70]:
att_model.predict((X_start_A, X_start_B))

array([[0.04806693, 0.0479217 , 0.0482955 , 0.04863629, 0.04889583,
        0.04933615, 0.04949446, 0.04913004, 0.04967229, 0.04977289,
        0.04988996, 0.05001303, 0.05070541, 0.05095737, 0.05157588,
        0.05172214, 0.05159759, 0.05125884, 0.05164228, 0.05141547]],
      dtype=float32)

In [191]:
sub_model.predict(X_start_A)

array([[0.00571418, 0.00576093, 0.00670105, 0.00754772, 0.00909929,
        0.01285915, 0.01515933, 0.01924153, 0.02778253, 0.03087712,
        0.03801217, 0.04425151, 0.04236898, 0.04851086, 0.04146721,
        0.04249327, 0.0456176 , 0.05001752, 0.05092429, 0.05524354,
        0.04319492, 0.04571097, 0.04449021, 0.04673455, 0.04125574,
        0.04386832, 0.0410103 , 0.03868463, 0.02597555, 0.02942494]],
      dtype=float32)

In [78]:
out_A = tf.reshape(X[20,:-1],[1,30])
history = sub_model.fit(X_start_A,out_A)

1/1 [==============================] - 0s 997us/step - loss: 3.0385


In [192]:
X_start_A = tf.reshape(X[9000:9020,:],[1,20,31])
output_A = sub_model.predict(X_start_A).reshape([30,])
output_A

array([0.00562455, 0.00574463, 0.00668056, 0.00753776, 0.0091731 ,
       0.01257379, 0.01475128, 0.01957747, 0.02798583, 0.03070259,
       0.03777093, 0.0445409 , 0.04266191, 0.04840747, 0.04168428,
       0.04331362, 0.04564666, 0.0493383 , 0.05078552, 0.05478575,
       0.04264643, 0.04581724, 0.04445539, 0.04604835, 0.04204214,
       0.04367106, 0.04185832, 0.03850069, 0.02602573, 0.02964774],
      dtype=float32)

In [115]:
pred_A_class_random = np.random.choice(30, 1, p=output_A)[0]
pred_A_class_random

26

In [119]:
one_hot = tf.reshape(tf.one_hot(pred_A_class_random, 30),[1,1,30])
out_0 = tf.concat((one_hot,[[[0]]]),2)
out_0

<tf.Tensor: shape=(1, 1, 31), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]],
      dtype=float32)>

In [124]:
sequence = X_start_A
sequence = tf.concat((sequence,out_0),1)

<tf.Tensor: shape=(1, 21, 31), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0.,

In [193]:
y_pred_A, y_pred_B = model.predict((X_start_A,out_0))
print('y_pred_A:',y_pred_A, 'y_pred_B:',y_pred_B)

y_pred_A: [[0.0002765  0.00043334 0.00040457 0.00069469 0.00051682 0.00046351
  0.00057519 0.00063459 0.00068334 0.00137723 0.00206947 0.00411383
  0.00614368 0.0085591  0.01278596 0.01632692 0.0214982  0.03857156
  0.04984158 0.06143961 0.06356119 0.08601837 0.08164802 0.09877734
  0.09345005 0.08831961 0.08210105 0.07336163 0.04988647 0.05546666]] y_pred_B: [[6.8537161e-06 1.4443988e-04 8.0808473e-05 3.4123881e-05 2.4863728e-05
  7.1276609e-06 1.6160871e-04 4.2995796e-04 2.9981358e-04 5.3690420e-04
  4.2272732e-04 2.4410681e-04 2.0895947e-03 3.9483807e-03 2.9393965e-03
  3.1873684e-03 6.3587935e-03 2.6323944e-01 1.4912690e-01 4.8175328e-03
  9.2510357e-03 6.9997534e-02 2.1094139e-01 1.6499990e-01 1.9481773e-02
  1.1417845e-02 7.1839094e-02 2.6789189e-03 9.8583265e-04 3.0596548e-04]]


In [121]:
output_B = y_pred_B.reshape([30,])
pred_B_class_random = np.random.choice(30, 1, p=output_B)[0]
pred_B_class_random

24

In [123]:
one_hot = tf.reshape(tf.one_hot(pred_B_class_random, 30),[1,1,30])
out_1 = tf.concat((one_hot,[[[1]]]),2)
out_1

<tf.Tensor: shape=(1, 1, 31), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.]]],
      dtype=float32)>

In [125]:
sequence = tf.concat((sequence,out_1),1)

In [127]:
sequence.shape

TensorShape([1, 22, 31])

In [129]:
X_start_A = sequence[:,-20:,:]
X_start_A.shape

TensorShape([1, 20, 31])

In [194]:
def generate_sequence(initial,seq_length):
    """
    Arguments:
    initial -- initial sequence of shape (1,20,31) (1 sample, sequence of length 20, vector fearure: one-hot(30);cantus(0),counter(1))
    seq_length -- # pairs of notes generated
    
    """
    ### START CODE HERE ###
    sequence = initial
    for i in range(seq_length):
        output_A = sub_model.predict(initial).reshape([30,])
        pred_A_class_random = np.random.choice(30, 1, p=output_A)[0]

        one_hot = tf.reshape(tf.one_hot(pred_A_class_random, 30),[1,1,30])
        out_0 = tf.concat((one_hot,[[[0]]]),2)
        sequence = tf.concat((sequence,out_0),1)

        y_pred_A, y_pred_B = model.predict((X_start_A,out_0))
        output_B = y_pred_B.reshape([30,])
        pred_B_class_random = np.random.choice(30, 1, p=output_B)[0]

        one_hot = tf.reshape(tf.one_hot(pred_B_class_random, 30),[1,1,30])
        out_1 = tf.concat((one_hot,[[[1]]]),2)
        sequence = tf.concat((sequence,out_1),1)

        initial = sequence[:,-20:,:]
        
    return sequence

In [195]:
X_start_A = tf.reshape(X[9000:9020,:],[1,20,31])
seq_length = 10
sequence = generate_sequence(X_start_A,seq_length)

In [196]:
new_sequence = sequence[:,20:,:]
sequence

<tf.Tensor: shape=(1, 40, 31), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]], dtype=float32)>

In [197]:
sequence = tf.reshape(sequence,[20+2*seq_length,31])
sequence = np.array(sequence)
sequence.shape

(40, 31)

In [198]:
np.where(sequence[1,:-1] == 1)[0][0]

12

In [199]:
row,col = sequence.shape
cantus_lst = [];
counter_lst = [];
for i in range(row):
    clas = np.where(sequence[i,:-1] == 1)[0][0]
    if sequence[i,-1] == 0:
        cantus_lst.append(clas+43)
    elif sequence[i,-1] == 1:
        counter_lst.append(clas+55)

In [200]:
cantus_lst

[63,
 62,
 58,
 56,
 59,
 62,
 61,
 59,
 62,
 72,
 65,
 61,
 58,
 67,
 62,
 72,
 46,
 51,
 62,
 64]

In [201]:
counter_lst

[67,
 65,
 67,
 64,
 62,
 70,
 69,
 68,
 71,
 75,
 74,
 69,
 67,
 76,
 66,
 81,
 74,
 63,
 69,
 72]

In [202]:
s = Session()
s.tempo = 180
piano1 = s.new_part("piano")
piano2 = s.new_part("piano")

def cantus():
    for i in cantus_lst:
        piano2.play_note(i,1,4)
        
def counter():
    for i in counter_lst:
        piano1.play_note(i,1,4)
        
        
s.fast_forward_to_beat(100)

s.start_transcribing()
s.fork(counter)
s.fork(cantus)
s.wait_for_children_to_finish()
performance = s.stop_transcribing()
performance.to_score(title = "First Species Counterpoint", composer = "My programme",time_signature = "4/4").show_xml()

Using preset Piano Merlin for piano
Using preset Piano Merlin for piano


In [203]:
np.array(counter_lst) - np.array(cantus_lst)

array([ 4,  3,  9,  8,  3,  8,  8,  9,  9,  3,  9,  8,  9,  9,  4,  9, 28,
       12,  7,  8], dtype=int64)

In [204]:
np.diff(cantus_lst)

array([ -1,  -4,  -2,   3,   3,  -1,  -2,   3,  10,  -7,  -4,  -3,   9,
        -5,  10, -26,   5,  11,   2], dtype=int64)

In [205]:
np.diff(counter_lst)

array([ -2,   2,  -3,  -2,   8,  -1,  -1,   3,   4,  -1,  -5,  -2,   9,
       -10,  15,  -7, -11,   6,   3], dtype=int64)