In [23]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import keras

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Softmax,Input

In [3]:
model = Sequential([
    Flatten(input_shape = (10,10)),
    Dense(16,activation = 'relu',name = "layer_1"),
    Dense(16,activation = "relu"),
    Dense(10,activation = "softmax")
])

In [4]:
model.weights

[<tf.Variable 'layer_1/kernel:0' shape=(100, 16) dtype=float32, numpy=
 array([[-0.11621615, -0.20894954,  0.21264568, ..., -0.10686608,
          0.02741823,  0.19421852],
        [ 0.08528543,  0.03080735,  0.12830293, ...,  0.0660691 ,
          0.1900051 , -0.17984003],
        [-0.11616832, -0.18449241,  0.17609769, ..., -0.11486598,
          0.12028018, -0.13370726],
        ...,
        [ 0.14384341, -0.14467362,  0.2032561 , ...,  0.20143864,
         -0.21612227, -0.04339944],
        [ 0.02007556,  0.15138799,  0.1689829 , ...,  0.0701462 ,
         -0.11633099,  0.14211708],
        [ 0.06277704,  0.13365227,  0.20092157, ..., -0.18363476,
         -0.01363187, -0.14405432]], dtype=float32)>,
 <tf.Variable 'layer_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 0.20590732, -0.18197522, -0.09607592,  0.10543

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 100)               0         
_________________________________________________________________
layer_1 (Dense)              (None, 16)                1616      
_________________________________________________________________
dense (Dense)                (None, 16)                272       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                170       
Total params: 2,058
Trainable params: 2,058
Non-trainable params: 0
_________________________________________________________________


In [6]:
hidden1 = model.layers[1]
hidden1.name

'layer_1'

In [7]:
model.get_layer('flatten')

In [10]:
weights, biases = hidden1.get_weights()
weights.shape

(100, 16)

In [12]:
biases.shape

(16,)

In [13]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

In [14]:
history = model.fit(X_train, y_train, epochs=30,
              validation_data=(X_valid, y_valid))

NameError: name 'X_train' is not defined

In [16]:
history.params
history.epoch

NameError: name 'history' is not defined

In [17]:
pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1) # set the vertical range to [0-1]
plt.show()

NameError: name 'history' is not defined

In [18]:
model.evaluate(X_test, y_test)

NameError: name 'X_test' is not defined

In [19]:
X_new = X_test[:3]
y_proba = model.predict(X_new)
y_proba.round(2)

NameError: name 'X_test' is not defined

In [20]:
y_pred = model.predict_classes(X_new) # class with highest posibility

NameError: name 'X_new' is not defined

In [21]:
model.save("my_keras_model.h5")

In [24]:
model = keras.models.load_model("my_keras_model.h5")

In [25]:
checkpoint_cb = keras.callbacks.ModelCheckpoint("my_keras_model.h5",save_best_only=True)
history = model.fit(X_train, y_train, epochs=10, 
                    validation_data=(X_valid, y_valid), 
                    callbacks=[checkpoint_cb])
model = keras.models.load_model("my_keras_model.h5")

NameError: name 'X_train' is not defined

In [26]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=10,
                                                  restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=100,
                    validation_data=(X_valid, y_valid),
                    callbacks=[checkpoint_cb, early_stopping_cb])

NameError: name 'X_train' is not defined