In [6]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import keras
import numpy as np

In [3]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
t.shape

TensorShape([2, 3])

In [4]:
t.dtype

tf.float32

In [10]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [11]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [12]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [13]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [14]:
t @ tf.transpose(t) # @ is matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [4]:
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [7]:
a = np.array([2., 4., 5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [8]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [10]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [11]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [26]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [14]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [18]:
v[:, 2].assign([0, 1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [19]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [23]:
v.assign_add(v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[200.,  84.,   0.],
       [ 16.,  20., 400.]], dtype=float32)>

In [27]:
v.assign_sub(v/2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]], dtype=float32)>

Dataset

In [47]:
X = tf.Variable(np.zeros((2,20)))  # any data tensor
X

<tf.Variable 'Variable:0' shape=(2, 20) dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])>

In [48]:
X[0,:].assign(np.concatenate((np.arange(10),np.arange(10))))

<tf.Variable 'UnreadVariable' shape=(2, 20) dtype=float64, numpy=
array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1., 2., 3., 4., 5.,
        6., 7., 8., 9.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])>

In [49]:
X[1,:].assign(np.concatenate((np.zeros(10),np.ones(10))))

<tf.Variable 'UnreadVariable' shape=(2, 20) dtype=float64, numpy=
array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1., 2., 3., 4., 5.,
        6., 7., 8., 9.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])>

In [64]:
dataset = tf.data.Dataset.from_tensor_slices(tf.transpose(X))
dataset

<TensorSliceDataset shapes: (2,), types: tf.float64>

In [65]:
for item in dataset:
    print(item)

tf.Tensor([0. 0.], shape=(2,), dtype=float64)
tf.Tensor([1. 0.], shape=(2,), dtype=float64)
tf.Tensor([2. 0.], shape=(2,), dtype=float64)
tf.Tensor([3. 0.], shape=(2,), dtype=float64)
tf.Tensor([4. 0.], shape=(2,), dtype=float64)
tf.Tensor([5. 0.], shape=(2,), dtype=float64)
tf.Tensor([6. 0.], shape=(2,), dtype=float64)
tf.Tensor([7. 0.], shape=(2,), dtype=float64)
tf.Tensor([8. 0.], shape=(2,), dtype=float64)
tf.Tensor([9. 0.], shape=(2,), dtype=float64)
tf.Tensor([0. 1.], shape=(2,), dtype=float64)
tf.Tensor([1. 1.], shape=(2,), dtype=float64)
tf.Tensor([2. 1.], shape=(2,), dtype=float64)
tf.Tensor([3. 1.], shape=(2,), dtype=float64)
tf.Tensor([4. 1.], shape=(2,), dtype=float64)
tf.Tensor([5. 1.], shape=(2,), dtype=float64)
tf.Tensor([6. 1.], shape=(2,), dtype=float64)
tf.Tensor([7. 1.], shape=(2,), dtype=float64)
tf.Tensor([8. 1.], shape=(2,), dtype=float64)
tf.Tensor([9. 1.], shape=(2,), dtype=float64)


In [66]:
dataset = dataset.repeat(3).batch(7,drop_remainder=True)
for item in dataset.take(3):
    print(item)

tf.Tensor(
[[0. 0.]
 [1. 0.]
 [2. 0.]
 [3. 0.]
 [4. 0.]
 [5. 0.]
 [6. 0.]], shape=(7, 2), dtype=float64)
tf.Tensor(
[[7. 0.]
 [8. 0.]
 [9. 0.]
 [0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]], shape=(7, 2), dtype=float64)
tf.Tensor(
[[4. 1.]
 [5. 1.]
 [6. 1.]
 [7. 1.]
 [8. 1.]
 [9. 1.]
 [0. 0.]], shape=(7, 2), dtype=float64)


In [67]:
dataset = tf.data.Dataset.unbatch(dataset)
dataset

<_UnbatchDataset shapes: (2,), types: tf.float64>

In [69]:
for item in dataset.take(3):
    print(item)

tf.Tensor([0. 0.], shape=(2,), dtype=float64)
tf.Tensor([1. 0.], shape=(2,), dtype=float64)
tf.Tensor([2. 0.], shape=(2,), dtype=float64)
